"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Cliente_1 = require("./Cliente");
var GeradorPessoas_1 = require("./GeradorPessoas");
var Pessoa_1 = require("./Pessoa");
var Guerreira_1 = require("./Guerreira");
var Monstro_1 = require("./Monstro");
var pess = new Pessoa_1.Pessoa();
var ciente1 = new Cliente_1.Cliente("Barlsessi", "Có", 23, "000.090.000-54", 2018116025);
var pessoa1 = new Pessoa_1.Pessoa("Lugó", "Turma de amendoim", 44, "999.090.000-00");
var gerador = new GeradorPessoas_1.GeradorPessoas();
gerador.inserirPessoa(pessoa1);
console.log(gerador.listar);
console.log(ciente1.apresentar());
var guerreira = new Guerreira_1.Guerreira("Guerreira", 100, 1000);
var monstro = new Monstro_1.Monstro("Monstro", 87, 1000);
guerreira.atacar(monstro);
guerreira.atacar(monstro);
guerreira.atacar(monstro);
monstro.atacar(guerreira);
